name: SensorServer

on:
  workflow_dispatch:
  repository_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Create google-services.json
        run: echo '${{ secrets.GOOGLE_SERVICES_JSON }}' > app/google-services.json
      - name: Build
        run: ./gradlew build
      - name: Deploy to Alpha
        uses: r0adkll/upload-google-play@v1.0.15
        with:
       #   serviceAccountJson: service_account.json
          packageName: com.sergiobelda.androidtodometer
          releaseFile: app/build/outputs/bundle/release/app-release.aab
          track: alpha
     # - name: Tag Release
     #   run: |
     #     version_name=${GITHUB_REF##*/}
     #     echo "Tagging release with tag $version_name"
     #     git tag $version_name release/$version_name
     #     git push origin --tags
